import { atom } from 'recoil'
export const nonMemberState = atom({
  key: 'nonMemberState',
  default: [
    {
      id: 1,
      email: 'jspark@outlook.com',
      userName: '박준서',
      phoneNumber: '010-3121-5138',
      role: 'ROLE_ADMIN',
      vacationCount: 15,
      position: '팀장',
      department: '개발팀',
      approved: false,
    },
    {
      id: 2,
      email: 'young2122@naver.com',
      userName: '이영수',
      phoneNumber: '010-5542-1233',
      role: 'ROLE_USER',
      vacationCount: 0,
      position: '부장',
      department: '개발팀',
      approved: false,
    },
    {
      id: 3,
      email: 'taekim333@naver.com',
      userName: '김태희',
      phoneNumber: '010-1233-1222',
      role: 'ROLE_USER',
      vacationCount: 9,
      position: '팀원',
      department: '프론트',
      approved: false,
    },
    {
      id: 4,
      email: 'singsong32@gmail.com',
      userName: '송혜진',
      phoneNumber: '010-3211-7344',
      role: 'ROLE_USER',
      vacationCount: 9,
      position: '사원',
      department: '개발',
      approved: false,
    },
    {
      id: 5,
      email: 'iamsujin@gmail.com',
      userName: '임수진',
      phoneNumber: '010-4223-2422',
      role: 'ROLE_USER',
      vacationCount: 34,
      position: '팀장',
      department: 'Back-End',
      approved: false,
    },
    {
      id: 6,
      email: 'hong123@abc.com',
      userName: '홍성민',
      phoneNumber: '010-2314-7857',
      role: 'ROLE_USER',
      vacationCount: 12,
      position: '사원',
      department: '재무팀',
      approved: false,
    },
    {
      id: 6,
      email: 'minji1212@abc.com',
      userName: '정민지',
      phoneNumber: '010-3456-7857',
      role: 'ROLE_USER',
      vacationCount: 12,
      position: '사원',
      department: '재무팀',
      approved: false,
    },
    {
      id: 6,
      email: 'ziwon100@icloud.com',
      userName: '백지원',
      phoneNumber: '010-3411-1234',
      role: 'ROLE_USER',
      vacationCount: 12,
      position: '사원',
      department: '재무팀',
      approved: false,
    },
  ],
})

export const usersState = atom({
  key: 'usersState',
  default: [
    {
      id: 1,
      email: 'hyeji@abc.com',
      userName: '공치기',
      phoneNumber: '010-8751-9138',
      role: 'ROLE_ADMIN',
      vacationCount: 15,
      position: '팀장',
      department: '개발팀',
    },
    {
      id: 2,
      email: 'hyein@naver.com',
      userName: '김혜인인',
      phoneNumber: '010-1234-5678',
      role: 'ROLE_USER',
      vacationCount: 0,
      position: '부장',
      department: '개발팀',
    },
    {
      id: 3,
      email: 'test100@naver.com',
      userName: '혜원',
      phoneNumber: '010-1234-1222',
      role: 'ROLE_USER',
      vacationCount: 9,
      position: '팀원',
      department: '프론트',
    },
    {
      id: 4,
      email: 'jisooround123@jisooround.com',
      userName: '송혜교',
      phoneNumber: '010-5028-7344',
      role: 'ROLE_USER',
      vacationCount: 9,
      position: '사원',
      department: '개발',
    },
    {
      id: 5,
      email: 'gram753@gmail.com',
      userName: '이승환',
      phoneNumber: '010-1111-2222',
      role: 'ROLE_USER',
      vacationCount: 34,
      position: '팀장',
      department: 'Back-End',
    },
    {
      id: 6,
      email: 'manman@abc.com',
      userName: '만만이',
      phoneNumber: '010-3456-7857',
      role: 'ROLE_USER',
      vacationCount: 12,
      position: '사원',
      department: '재무팀',
    },
  ],
})
export const eventsState = atom({
  key: 'eventsState',
  default: [
    {
      id: 43,
      category: 'WORK',
      user: {
        createdAt: '2023-04-01T09:45:21.835961',
        modifiedAt: '2023-04-04T08:48:40.991376',
        id: 4,
        email: 'jisooround123@jisooround.com',
        userName: '송혜교',
        password: '$2a$10$POOOM6xY/sOz9eBOesejIORODNkEiVZjv7CtkcF8G2zrGidEvtQcG',
        phoneNumber: '010-5028-7344',
        role: 'ROLE_USER',
        vacationCount: 9,
        position: '사원',
        department: '개발',
        enabled: true,
        username: '송혜교',
        accountNonLocked: true,
        authorities: [
          {
            authority: 'USER',
          },
        ],
        accountNonExpired: true,
        credentialsNonExpired: true,
      },
      startDate: '2023-04-08',
      endDate: '2023-04-08',
      memo: '개인 업무',
      status: 'WAITING',
    },
    {
      id: 42,
      category: 'VACATION',
      user: {
        createdAt: '2023-04-01T09:45:21.835961',
        modifiedAt: '2023-04-04T08:48:40.991376',
        id: 4,
        email: 'jisooround123@jisooround.com',
        userName: '송혜교',
        password: '$2a$10$POOOM6xY/sOz9eBOesejIORODNkEiVZjv7CtkcF8G2zrGidEvtQcG',
        phoneNumber: '010-5028-7344',
        role: 'ROLE_USER',
        vacationCount: 9,
        position: '사원',
        department: '개발',
        enabled: true,
        username: '송혜교',
        accountNonLocked: true,
        authorities: [
          {
            authority: 'USER',
          },
        ],
        accountNonExpired: true,
        credentialsNonExpired: true,
      },
      startDate: '2023-04-04',
      endDate: '2023-04-06',
      memo: '정규 스케쥴',
      status: 'WAITING',
    },
    {
      id: 37,
      category: 'WORK',
      user: {
        createdAt: '2023-04-01T09:45:21.835961',
        modifiedAt: '2023-04-04T08:48:40.991376',
        id: 4,
        email: 'jisooround123@jisooround.com',
        userName: '송혜교',
        password: '$2a$10$POOOM6xY/sOz9eBOesejIORODNkEiVZjv7CtkcF8G2zrGidEvtQcG',
        phoneNumber: '010-5028-7344',
        role: 'ROLE_USER',
        vacationCount: 9,
        position: '사원',
        department: '개발',
        enabled: true,
        username: '송혜교',
        accountNonLocked: true,
        authorities: [
          {
            authority: 'USER',
          },
        ],
        accountNonExpired: true,
        credentialsNonExpired: true,
      },
      startDate: '2023-04-08',
      endDate: '2023-04-08',
      memo: '병원 방문',
      status: 'PERMIT',
    },
    {
      id: 35,
      category: 'VACATION',
      user: {
        createdAt: '2023-04-01T09:45:21.835961',
        modifiedAt: '2023-04-04T08:48:40.991376',
        id: 4,
        email: 'jisooround123@jisooround.com',
        userName: '송혜교',
        password: '$2a$10$POOOM6xY/sOz9eBOesejIORODNkEiVZjv7CtkcF8G2zrGidEvtQcG',
        phoneNumber: '010-5028-7344',
        role: 'ROLE_USER',
        vacationCount: 9,
        position: '사원',
        department: '개발',
        enabled: true,
        username: '송혜교',
        accountNonLocked: true,
        authorities: [
          {
            authority: 'USER',
          },
        ],
        accountNonExpired: true,
        credentialsNonExpired: true,
      },
      startDate: '2023-04-04',
      endDate: '2023-04-06',
      memo: '정규 스케쥴',
      status: 'WAITING',
    },
    {
      id: 20,
      category: 'WORK',
      user: {
        createdAt: '2023-04-01T09:45:21.835961',
        modifiedAt: '2023-04-04T08:48:40.991376',
        id: 4,
        email: 'jisooround123@jisooround.com',
        userName: '송혜교',
        password: '$2a$10$POOOM6xY/sOz9eBOesejIORODNkEiVZjv7CtkcF8G2zrGidEvtQcG',
        phoneNumber: '010-5028-7344',
        role: 'ROLE_USER',
        vacationCount: 9,
        position: '사원',
        department: '개발',
        enabled: true,
        username: '송혜교',
        accountNonLocked: true,
        authorities: [
          {
            authority: 'USER',
          },
        ],
        accountNonExpired: true,
        credentialsNonExpired: true,
      },
      startDate: '2023-04-02',
      endDate: '2023-04-02',
      memo: '개인 업무',
      status: 'WAITING',
    },
  ],
})

export const scheduleState = atom({
  key: 'scheduleState',
  default: [
    {
      species: '연차',
      person: '공혜지',
      level: '인사팀/사원',
      reason: '병원 방문',
      date: '2023.01.25',
      state: '처리대기',
    },
    {
      species: '당직',
      person: '공혜지',
      level: '개발팀/사원',
      reason: '각종 경조사',
      date: '2023.01.25',
      state: '승인',
    },
    {
      species: '연차',
      person: '규규규',
      level: '개발팀/사원',
      reason: '개인 업무',
      date: '2023.01.25',
      state: '거절',
    },
    {
      species: '연차',
      person: '우지수',
      level: '개발팀/사원',
      reason: '개인 업무',
      date: '2023.01.25',
      state: '거절',
    },
    {
      species: '당직',
      person: '홍혜원',
      level: '인사팀/사원',
      reason: '각종 경조사',
      date: '2023.01.26',
      state: '처리대기',
    },
  ],
})

export const adminsSchedulesState = atom({
  key: 'adminsSchedulesState',
  default: [
    {
      id: 48,
      category: 'VACATION',
      user: {
        createdAt: '2023-04-04T04:36:27.331836',
        modifiedAt: '2023-04-04T10:31:52.398061',
        id: 46,
        email: 'abcd@abcd.com',
        userName: '프링글스',
        password: '$2a$10$UUEQbM9o.j.SklMqFLSzUuDf1yy1tUihKjQwxniPsTdDXe1wuOZge',
        phoneNumber: '010-1111-2222',
        role: 'ROLE_ADMIN',
        vacationCount: 11,
        position: '사원',
        department: '개발',
        enabled: true,
        username: '프링글스',
        accountNonLocked: true,
        authorities: [
          {
            authority: 'ADMIN',
          },
        ],
        accountNonExpired: true,
        credentialsNonExpired: true,
      },
      startDate: '2023-04-01',
      endDate: '2023-04-04',
      memo: '롤 5인팟 약속있음',
      status: 'WAITING',
    },
    {
      id: 45,
      category: 'WORK',
      user: {
        createdAt: '2023-04-01T10:37:34.038444',
        modifiedAt: '2023-04-02T21:19:37.235774',
        id: 5,
        email: 'gram753@gmail.com',
        userName: '이승환',
        password: '$2a$10$67arl7T5C4lx/n1waS2sLuLGEGPFhFTrn9LwrSbCmEkOZu5/FcBXS',
        phoneNumber: '010-1111-2222',
        role: 'ROLE_USER',
        vacationCount: 34,
        position: '팀장',
        department: 'Back-End',
        enabled: true,
        username: '이승환',
        accountNonLocked: true,
        authorities: [
          {
            authority: 'USER',
          },
        ],
        accountNonExpired: true,
        credentialsNonExpired: true,
      },
      startDate: '2023-04-02',
      endDate: '2023-04-02',
      memo: 'sssssg',
      status: 'WAITING',
    },
    {
      id: 43,
      category: 'WORK',
      user: {
        createdAt: '2023-04-01T09:45:21.835961',
        modifiedAt: '2023-04-04T08:48:40.991376',
        id: 4,
        email: 'jisooround123@jisooround.com',
        userName: '송혜교',
        password: '$2a$10$POOOM6xY/sOz9eBOesejIORODNkEiVZjv7CtkcF8G2zrGidEvtQcG',
        phoneNumber: '010-5028-7344',
        role: 'ROLE_USER',
        vacationCount: 9,
        position: '사원',
        department: '개발',
        enabled: true,
        username: '송혜교',
        accountNonLocked: true,
        authorities: [
          {
            authority: 'USER',
          },
        ],
        accountNonExpired: true,
        credentialsNonExpired: true,
      },
      startDate: '2023-04-08',
      endDate: '2023-04-08',
      memo: '개인 업무',
      status: 'WAITING',
    },
    {
      id: 42,
      category: 'VACATION',
      user: {
        createdAt: '2023-04-01T09:45:21.835961',
        modifiedAt: '2023-04-04T08:48:40.991376',
        id: 4,
        email: 'jisooround123@jisooround.com',
        userName: '송혜교',
        password: '$2a$10$POOOM6xY/sOz9eBOesejIORODNkEiVZjv7CtkcF8G2zrGidEvtQcG',
        phoneNumber: '010-5028-7344',
        role: 'ROLE_USER',
        vacationCount: 9,
        position: '사원',
        department: '개발',
        enabled: true,
        username: '송혜교',
        accountNonLocked: true,
        authorities: [
          {
            authority: 'USER',
          },
        ],
        accountNonExpired: true,
        credentialsNonExpired: true,
      },
      startDate: '2023-04-04',
      endDate: '2023-04-06',
      memo: '정규 스케쥴',
      status: 'WAITING',
    },
    {
      id: 41,
      category: 'VACATION',
      user: {
        createdAt: '2023-04-01T10:37:34.038444',
        modifiedAt: '2023-04-02T21:19:37.235774',
        id: 5,
        email: 'gram753@gmail.com',
        userName: '이승환',
        password: '$2a$10$67arl7T5C4lx/n1waS2sLuLGEGPFhFTrn9LwrSbCmEkOZu5/FcBXS',
        phoneNumber: '010-1111-2222',
        role: 'ROLE_USER',
        vacationCount: 34,
        position: '팀장',
        department: 'Back-End',
        enabled: true,
        username: '이승환',
        accountNonLocked: true,
        authorities: [
          {
            authority: 'USER',
          },
        ],
        accountNonExpired: true,
        credentialsNonExpired: true,
      },
      startDate: '2023-04-06',
      endDate: '2023-04-04',
      memo: '제발....',
      status: 'WAITING',
    },
  ],
})